### ISSUE TITLE
M3U8 Video not getting played in Chrome/Web

### ISSUE THREAD

**Issue by NehaKushwah993** [GeekyAnts/flick-video-player#148]
Hi,

following m3u8 is not getting played in Web :

https://multiplatform-f.akamaihd.net/i/multi/will/bunny/big_buck_bunny_,640x360_400,640x360_700,640x360_1000,950x540_1500,.f4v.csmil/master.m3u8

getting error in player.

**Comment by abdmhamzah** [comment]
my network video also not getting loaded with this with this cool plugins
I use this plugin on flutter web and use safari to perform the test, there is error 

Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

**Comment by NehaKushwah993** [comment]
same for me!
